#define OCAML_STACK_WOSIZE                64
#define OCAML_STATIC_HEAP_WOSIZE          16
#define OCAML_DYNAMIC_HEAP_WOSIZE        240
#define OCAML_FLASH_HEAP_WOSIZE          177
#define OCAML_STACK_INITIAL_WOSIZE         1
#define OCAML_RAM_GLOBDATA_NUMBER          0
#define OCAML_FLASH_GLOBDATA_NUMBER       29
#define OCAML_BYTECODE_BSIZE             627
#define OCAML_PRIMITIVE_NUMBER             9
#define OCAML_VIRTUAL_ARCH                32
#define OCAML_STARTING_OOID                1
#define OCAML_NO_FLASH_HEAP                0
#define OCAML_NO_FLASH_GLOBALS             0

#define OCAML_GC_MARK_AND_COMPACT

#include </Users/ruiwenwang/Desktop/OMicroB/src/byterun/vm/values.h>

#define OCAML_ACC0                        0
#define OCAML_ACC1                        1
#define OCAML_ACC2                        2
#define OCAML_ACC4                        3
#define OCAML_ACC5                        4
#define OCAML_PUSH                        5
#define OCAML_PUSHACC1                    6
#define OCAML_PUSHACC2                    7
#define OCAML_PUSHACC3                    8
#define OCAML_PUSHACC4                    9
#define OCAML_PUSHACC5                   10
#define OCAML_PUSHACC6                   11
#define OCAML_PUSHACC7                   12
#define OCAML_PUSHACC                    13
#define OCAML_POP                        14
#define OCAML_ASSIGN                     15
#define OCAML_PUSHENVACC1                16
#define OCAML_APPLY1                     17
#define OCAML_APPLY2                     18
#define OCAML_APPLY3                     19
#define OCAML_APPTERM                    20
#define OCAML_APPTERM1                   21
#define OCAML_APPTERM2                   22
#define OCAML_APPTERM3                   23
#define OCAML_RETURN                     24
#define OCAML_RESTART                    25
#define OCAML_GRAB                       26
#define OCAML_CLOSURE_1B                 27
#define OCAML_CLOSUREREC_1B              28
#define OCAML_PUSHOFFSETCLOSURE0         29
#define OCAML_GETFLASHGLOBAL_1B          30
#define OCAML_PUSHGETFLASHGLOBAL_1B      31
#define OCAML_MAKEBLOCK2                 32
#define OCAML_GETFIELD0                  33
#define OCAML_GETFIELD1                  34
#define OCAML_GETFIELD                   35
#define OCAML_SETBYTESCHAR               36
#define OCAML_BRANCH_1B                  37
#define OCAML_BRANCH_2B                  38
#define OCAML_BRANCHIF_1B                39
#define OCAML_BRANCHIFNOT_1B             40
#define OCAML_RAISE                      41
#define OCAML_CHECK_SIGNALS              42
#define OCAML_C_CALL1                    43
#define OCAML_C_CALL3                    44
#define OCAML_C_CALL5                    45
#define OCAML_CONST0                     46
#define OCAML_CONST1                     47
#define OCAML_CONSTINT_1B                48
#define OCAML_CONSTINT_2B                49
#define OCAML_PUSHCONST0                 50
#define OCAML_PUSHCONST3                 51
#define OCAML_PUSHCONSTINT_1B            52
#define OCAML_ADDINT                     53
#define OCAML_NEQ                        54
#define OCAML_LTINT                      55
#define OCAML_GTINT                      56
#define OCAML_GEINT                      57
#define OCAML_OFFSETINT_1B               58
#define OCAML_BLEINT_1B                  59
#define OCAML_BGTINT_1B                  60
#define OCAML_BGEINT_2B                  61
#define OCAML_STOP                       62

value ocaml_stack[OCAML_STACK_WOSIZE];
value ocaml_ram_heap[OCAML_STATIC_HEAP_WOSIZE + OCAML_DYNAMIC_HEAP_WOSIZE];
value ocaml_ram_global_data[OCAML_RAM_GLOBDATA_NUMBER];

PROGMEM value const ocaml_flash_heap[OCAML_FLASH_HEAP_WOSIZE] = {
  /*   0 */  Make_header(0, 0, Color_white),
  /*   1 */  Make_header(2, Object_tag, Color_white),
  /*   2 */  Val_flash_block(&ocaml_flash_heap[5]),
  /*   3 */  Val_int(-1),
  /*   4 */  Make_header(4, String_tag, Color_white),
  /*   5 */  Make_string_data('O', 'u', 't', '_'),
  /*   6 */  Make_string_data('o', 'f', '_', 'm'),
  /*   7 */  Make_string_data('e', 'm', 'o', 'r'),
  /*   8 */  Make_string_data('y', '\0', '\0', '\2'),
  /*   9 */  Make_header(2, Object_tag, Color_white),
  /*  10 */  Val_flash_block(&ocaml_flash_heap[13]),
  /*  11 */  Val_int(-3),
  /*  12 */  Make_header(2, String_tag, Color_white),
  /*  13 */  Make_string_data('F', 'a', 'i', 'l'),
  /*  14 */  Make_string_data('u', 'r', 'e', '\0'),
  /*  15 */  Make_header(2, Object_tag, Color_white),
  /*  16 */  Val_flash_block(&ocaml_flash_heap[19]),
  /*  17 */  Val_int(-4),
  /*  18 */  Make_header(5, String_tag, Color_white),
  /*  19 */  Make_string_data('I', 'n', 'v', 'a'),
  /*  20 */  Make_string_data('l', 'i', 'd', '_'),
  /*  21 */  Make_string_data('a', 'r', 'g', 'u'),
  /*  22 */  Make_string_data('m', 'e', 'n', 't'),
  /*  23 */  Make_string_data('\0', '\0', '\0', '\3'),
  /*  24 */  Make_header(2, Object_tag, Color_white),
  /*  25 */  Val_flash_block(&ocaml_flash_heap[28]),
  /*  26 */  Val_int(-6),
  /*  27 */  Make_header(5, String_tag, Color_white),
  /*  28 */  Make_string_data('D', 'i', 'v', 'i'),
  /*  29 */  Make_string_data('s', 'i', 'o', 'n'),
  /*  30 */  Make_string_data('_', 'b', 'y', '_'),
  /*  31 */  Make_string_data('z', 'e', 'r', 'o'),
  /*  32 */  Make_string_data('\0', '\0', '\0', '\3'),
  /*  33 */  Make_header(2, Object_tag, Color_white),
  /*  34 */  Val_flash_block(&ocaml_flash_heap[37]),
  /*  35 */  Val_int(-9),
  /*  36 */  Make_header(4, String_tag, Color_white),
  /*  37 */  Make_string_data('S', 't', 'a', 'c'),
  /*  38 */  Make_string_data('k', '_', 'o', 'v'),
  /*  39 */  Make_string_data('e', 'r', 'f', 'l'),
  /*  40 */  Make_string_data('o', 'w', '\0', '\1'),
  /*  41 */  Make_header(1, Closure_tag, Color_white),
  /*  42 */  Val_codeptr(360),
  /*  43 */  Make_header(3, String_tag, Color_white),
  /*  44 */  Make_string_data('O', 'M', 'i', 'c'),
  /*  45 */  Make_string_data('r', 'o', 'B', '!'),
  /*  46 */  Make_string_data('\0', '\0', '\0', '\3'),
  /*  47 */  Make_header(3, String_tag, Color_white),
  /*  48 */  Make_string_data('C', 'h', 'a', 'r'),
  /*  49 */  Make_string_data('.', 'c', 'h', 'r'),
  /*  50 */  Make_string_data('\0', '\0', '\0', '\3'),
  /*  51 */  Make_header(1, Closure_tag, Color_white),
  /*  52 */  Val_codeptr(8),
  /*  53 */  Make_header(1, Closure_tag, Color_white),
  /*  54 */  Val_codeptr(175),
  /*  55 */  Make_header(1, Closure_tag, Color_white),
  /*  56 */  Val_codeptr(40),
  /*  57 */  Make_header(1, Closure_tag, Color_white),
  /*  58 */  Val_codeptr(79),
  /*  59 */  Make_header(4, String_tag, Color_white),
  /*  60 */  Make_string_data('B', 'y', 't', 'e'),
  /*  61 */  Make_string_data('s', '.', 'c', 'o'),
  /*  62 */  Make_string_data('n', 'c', 'a', 't'),
  /*  63 */  Make_string_data('\0', '\0', '\0', '\3'),
  /*  64 */  Make_header(1, Closure_tag, Color_white),
  /*  65 */  Val_codeptr(247),
  /*  66 */  Make_header(1, String_tag, Color_white),
  /*  67 */  Make_string_data('n', 't', 'h', '\0'),
  /*  68 */  Make_header(1, Closure_tag, Color_white),
  /*  69 */  Val_codeptr(14),
  /*  70 */  Make_header(3, String_tag, Color_white),
  /*  71 */  Make_string_data('L', 'i', 's', 't'),
  /*  72 */  Make_string_data('.', 'n', 't', 'h'),
  /*  73 */  Make_string_data('\0', '\0', '\0', '\3'),
  /*  74 */  Make_header(1, Closure_tag, Color_white),
  /*  75 */  Val_codeptr(230),
  /*  76 */  Make_header(3, String_tag, Color_white),
  /*  77 */  Make_string_data('w', 'r', 'i', 't'),
  /*  78 */  Make_string_data('e', '_', 'p', 'i'),
  /*  79 */  Make_string_data('x', 'e', 'l', '\0'),
  /*  80 */  Make_header(1, Closure_tag, Color_white),
  /*  81 */  Val_codeptr(333),
  /*  82 */  Make_header(1, Closure_tag, Color_white),
  /*  83 */  Val_codeptr(20),
  /*  84 */  Make_header(1, Closure_tag, Color_white),
  /*  85 */  Val_codeptr(354),
  /*  86 */  Make_header(3, String_tag, Color_white),
  /*  87 */  Make_string_data('p', 'r', 'i', 'n'),
  /*  88 */  Make_string_data('t', '_', 'i', 'm'),
  /*  89 */  Make_string_data('a', 'g', 'e', '\0'),
  /*  90 */  Make_header(1, Closure_tag, Color_white),
  /*  91 */  Val_codeptr(192),
  /*  92 */  Make_header(1, Closure_tag, Color_white),
  /*  93 */  Val_codeptr(287),
  /*  94 */  Make_header(1, Closure_tag, Color_white),
  /*  95 */  Val_codeptr(299),
  /*  96 */  Make_header(1, Closure_tag, Color_white),
  /*  97 */  Val_codeptr(145),
  /*  98 */  Make_header(1, Closure_tag, Color_white),
  /*  99 */  Val_codeptr(3),
  /* 100 */  Make_header(1, Closure_tag, Color_white),
  /* 101 */  Val_codeptr(497),
  /* 102 */  Make_header(1, Closure_tag, Color_white),
  /* 103 */  Val_codeptr(489),
  /* 104 */  Make_header(1, Closure_tag, Color_white),
  /* 105 */  Val_codeptr(486),
  /* 106 */  Make_header(1, Closure_tag, Color_white),
  /* 107 */  Val_codeptr(450),
  /* 108 */  Make_header(1, Closure_tag, Color_white),
  /* 109 */  Val_codeptr(365),
  /* 110 */  Make_header(1, Closure_tag, Color_white),
  /* 111 */  Val_codeptr(371),
  /* 112 */  Make_header(2, 0, Color_white),
  /* 113 */  Val_flash_block(&ocaml_flash_heap[116]),
  /* 114 */  Val_flash_block(&ocaml_flash_heap[131]),
  /* 115 */  Make_header(2, 0, Color_white),
  /* 116 */  Val_unit,
  /* 117 */  Val_flash_block(&ocaml_flash_heap[119]),
  /* 118 */  Make_header(2, 0, Color_white),
  /* 119 */  Val_int(1),
  /* 120 */  Val_flash_block(&ocaml_flash_heap[122]),
  /* 121 */  Make_header(2, 0, Color_white),
  /* 122 */  Val_unit,
  /* 123 */  Val_flash_block(&ocaml_flash_heap[125]),
  /* 124 */  Make_header(2, 0, Color_white),
  /* 125 */  Val_int(1),
  /* 126 */  Val_flash_block(&ocaml_flash_heap[128]),
  /* 127 */  Make_header(2, 0, Color_white),
  /* 128 */  Val_unit,
  /* 129 */  Val_unit,
  /* 130 */  Make_header(2, 0, Color_white),
  /* 131 */  Val_flash_block(&ocaml_flash_heap[116]),
  /* 132 */  Val_flash_block(&ocaml_flash_heap[134]),
  /* 133 */  Make_header(2, 0, Color_white),
  /* 134 */  Val_flash_block(&ocaml_flash_heap[137]),
  /* 135 */  Val_flash_block(&ocaml_flash_heap[149]),
  /* 136 */  Make_header(2, 0, Color_white),
  /* 137 */  Val_unit,
  /* 138 */  Val_flash_block(&ocaml_flash_heap[140]),
  /* 139 */  Make_header(2, 0, Color_white),
  /* 140 */  Val_unit,
  /* 141 */  Val_flash_block(&ocaml_flash_heap[143]),
  /* 142 */  Make_header(2, 0, Color_white),
  /* 143 */  Val_unit,
  /* 144 */  Val_flash_block(&ocaml_flash_heap[146]),
  /* 145 */  Make_header(2, 0, Color_white),
  /* 146 */  Val_unit,
  /* 147 */  Val_flash_block(&ocaml_flash_heap[128]),
  /* 148 */  Make_header(2, 0, Color_white),
  /* 149 */  Val_flash_block(&ocaml_flash_heap[137]),
  /* 150 */  Val_flash_block(&ocaml_flash_heap[152]),
  /* 151 */  Make_header(2, 0, Color_white),
  /* 152 */  Val_flash_block(&ocaml_flash_heap[155]),
  /* 153 */  Val_unit,
  /* 154 */  Make_header(2, 0, Color_white),
  /* 155 */  Val_int(1),
  /* 156 */  Val_flash_block(&ocaml_flash_heap[158]),
  /* 157 */  Make_header(2, 0, Color_white),
  /* 158 */  Val_int(1),
  /* 159 */  Val_flash_block(&ocaml_flash_heap[161]),
  /* 160 */  Make_header(2, 0, Color_white),
  /* 161 */  Val_int(1),
  /* 162 */  Val_flash_block(&ocaml_flash_heap[164]),
  /* 163 */  Make_header(2, 0, Color_white),
  /* 164 */  Val_int(1),
  /* 165 */  Val_flash_block(&ocaml_flash_heap[167]),
  /* 166 */  Make_header(2, 0, Color_white),
  /* 167 */  Val_int(1),
  /* 168 */  Val_unit,
  /* 169 */  Make_header(1, Closure_tag, Color_white),
  /* 170 */  Val_codeptr(513),
  /* 171 */  Make_header(1, Closure_tag, Color_white),
  /* 172 */  Val_codeptr(508),
  /* 173 */  Make_header(1, Closure_tag, Color_white),
  /* 174 */  Val_codeptr(505),
  /* 175 */  Make_header(1, Closure_tag, Color_white),
  /* 176 */  Val_codeptr(500)
};

PROGMEM value const ocaml_initial_static_heap[OCAML_STATIC_HEAP_WOSIZE] = {
  /*  0 */  Make_header(1, String_tag, Color_white),
  /*  1 */  Make_string_data('\0', '\0', '\0', '\3'),
  /*  2 */  Make_header(7, 0, Color_white),
  /*  3 */  Val_flash_block(&ocaml_flash_heap[101]),
  /*  4 */  Val_flash_block(&ocaml_flash_heap[103]),
  /*  5 */  Val_flash_block(&ocaml_flash_heap[42]),
  /*  6 */  Val_flash_block(&ocaml_flash_heap[105]),
  /*  7 */  Val_flash_block(&ocaml_flash_heap[107]),
  /*  8 */  Val_flash_block(&ocaml_flash_heap[109]),
  /*  9 */  Val_flash_block(&ocaml_flash_heap[111]),
  /* 10 */  Make_header(2, 0, Color_white),
  /* 11 */  Val_flash_block(&ocaml_flash_heap[170]),
  /* 12 */  Val_flash_block(&ocaml_flash_heap[172]),
  /* 13 */  Make_header(2, 0, Color_white),
  /* 14 */  Val_flash_block(&ocaml_flash_heap[174]),
  /* 15 */  Val_flash_block(&ocaml_flash_heap[176])
};

PROGMEM value const ocaml_initial_stack[OCAML_STACK_INITIAL_WOSIZE] = {
  /* 0 */  Val_flash_block(&ocaml_flash_heap[44])
};

PROGMEM value const ocaml_flash_global_data[OCAML_FLASH_GLOBDATA_NUMBER] = {
  /*  0 */  Val_flash_block(&ocaml_flash_heap[10]),
  /*  1 */  Val_flash_block(&ocaml_flash_heap[16]),
  /*  2 */  Val_flash_block(&ocaml_flash_heap[48]),
  /*  3 */  Val_flash_block(&ocaml_flash_heap[52]),
  /*  4 */  Val_flash_block(&ocaml_flash_heap[54]),
  /*  5 */  Val_flash_block(&ocaml_flash_heap[56]),
  /*  6 */  Val_flash_block(&ocaml_flash_heap[58]),
  /*  7 */  Val_static_block(&ocaml_ram_heap[1]),
  /*  8 */  Val_flash_block(&ocaml_flash_heap[60]),
  /*  9 */  Val_flash_block(&ocaml_flash_heap[65]),
  /* 10 */  Val_flash_block(&ocaml_flash_heap[67]),
  /* 11 */  Val_flash_block(&ocaml_flash_heap[69]),
  /* 12 */  Val_flash_block(&ocaml_flash_heap[71]),
  /* 13 */  Val_flash_block(&ocaml_flash_heap[75]),
  /* 14 */  Val_flash_block(&ocaml_flash_heap[77]),
  /* 15 */  Val_flash_block(&ocaml_flash_heap[81]),
  /* 16 */  Val_flash_block(&ocaml_flash_heap[83]),
  /* 17 */  Val_flash_block(&ocaml_flash_heap[85]),
  /* 18 */  Val_flash_block(&ocaml_flash_heap[87]),
  /* 19 */  Val_flash_block(&ocaml_flash_heap[91]),
  /* 20 */  Val_flash_block(&ocaml_flash_heap[87]),
  /* 21 */  Val_flash_block(&ocaml_flash_heap[93]),
  /* 22 */  Val_flash_block(&ocaml_flash_heap[95]),
  /* 23 */  Val_flash_block(&ocaml_flash_heap[97]),
  /* 24 */  Val_flash_block(&ocaml_flash_heap[99]),
  /* 25 */  Val_static_block(&ocaml_ram_heap[3]),
  /* 26 */  Val_flash_block(&ocaml_flash_heap[113]),
  /* 27 */  Val_static_block(&ocaml_ram_heap[11]),
  /* 28 */  Val_static_block(&ocaml_ram_heap[14])
};

value acc = Val_flash_block(&ocaml_flash_heap[42]);
value env = Val_unit;

#define OCAML_Out_of_memory        Val_flash_block(&ocaml_flash_heap[2])
#define OCAML_Failure              Val_flash_block(&ocaml_flash_heap[10])
#define OCAML_Invalid_argument     Val_flash_block(&ocaml_flash_heap[16])
#define OCAML_Division_by_zero     Val_flash_block(&ocaml_flash_heap[25])
#define OCAML_Stack_overflow       Val_flash_block(&ocaml_flash_heap[34])

#define OCAML_atom0                Val_flash_block(&ocaml_flash_heap[1])

PROGMEM opcode_t const ocaml_bytecode[OCAML_BYTECODE_BSIZE] = {
  /*   0 */  OCAML_BRANCH_2B, 2, 4,
  /*   3 */  OCAML_ACC0,
  /*   4 */  OCAML_C_CALL1, 0,
  /*   6 */  OCAML_RETURN, 1,
  /*   8 */  OCAML_ACC0,
  /*   9 */  OCAML_PUSHGETFLASHGLOBAL_1B, 1,
  /*  11 */  OCAML_MAKEBLOCK2, 0,
  /*  13 */  OCAML_RAISE,
  /*  14 */  OCAML_ACC0,
  /*  15 */  OCAML_PUSHGETFLASHGLOBAL_1B, 0,
  /*  17 */  OCAML_MAKEBLOCK2, 0,
  /*  19 */  OCAML_RAISE,
  /*  20 */  OCAML_ACC0,
  /*  21 */  OCAML_BGTINT_1B, 0, 9,
  /*  24 */  OCAML_ACC0,
  /*  25 */  OCAML_BGEINT_2B, 0, 255, 0, 11,
  /*  30 */  OCAML_GETFLASHGLOBAL_1B, 2,
  /*  32 */  OCAML_PUSHGETFLASHGLOBAL_1B, 3,
  /*  34 */  OCAML_APPTERM1, 2,
  /*  36 */  OCAML_ACC0,
  /*  37 */  OCAML_RETURN, 1,
  /*  39 */  OCAML_RESTART,
  /*  40 */  OCAML_GRAB, 2,
  /*  42 */  OCAML_ACC2,
  /*  43 */  OCAML_BRANCHIFNOT_1B, 32,
  /*  45 */  OCAML_ACC2,
  /*  46 */  OCAML_GETFIELD1,
  /*  47 */  OCAML_PUSHACC3,
  /*  48 */  OCAML_GETFIELD0,
  /*  49 */  OCAML_PUSHACC1,
  /*  50 */  OCAML_BRANCHIFNOT_1B, 18,
  /*  52 */  OCAML_ACC1,
  /*  53 */  OCAML_PUSHACC4,
  /*  54 */  OCAML_PUSHACC4,
  /*  55 */  OCAML_PUSHACC5,
  /*  56 */  OCAML_PUSHACC7,
  /*  57 */  OCAML_PUSHACC5,
  /*  58 */  OCAML_C_CALL1, 1,
  /*  60 */  OCAML_ADDINT,
  /*  61 */  OCAML_ADDINT,
  /*  62 */  OCAML_PUSHGETFLASHGLOBAL_1B, 4,
  /*  64 */  OCAML_APPLY2,
  /*  65 */  OCAML_PUSHOFFSETCLOSURE0,
  /*  66 */  OCAML_APPTERM3, 8,
  /*  68 */  OCAML_ACC2,
  /*  69 */  OCAML_PUSHACC1,
  /*  70 */  OCAML_C_CALL1, 1,
  /*  72 */  OCAML_ADDINT,
  /*  73 */  OCAML_RETURN, 5,
  /*  75 */  OCAML_ACC0,
  /*  76 */  OCAML_RETURN, 3,
  /*  78 */  OCAML_RESTART,
  /*  79 */  OCAML_GRAB, 4,
  /*  81 */  OCAML_ACC4,
  /*  82 */  OCAML_BRANCHIFNOT_1B, 59,
  /*  84 */  OCAML_ACC4,
  /*  85 */  OCAML_GETFIELD1,
  /*  86 */  OCAML_PUSHACC5,
  /*  87 */  OCAML_GETFIELD0,
  /*  88 */  OCAML_PUSHACC1,
  /*  89 */  OCAML_BRANCHIFNOT_1B, 40,
  /*  91 */  OCAML_ACC0,
  /*  92 */  OCAML_C_CALL1, 1,
  /*  94 */  OCAML_PUSHACC4,
  /*  95 */  OCAML_PUSHACC4,
  /*  96 */  OCAML_PUSHCONST0,
  /*  97 */  OCAML_PUSHACC4,
  /*  98 */  OCAML_C_CALL5, 2,
  /* 100 */  OCAML_ACC5,
  /* 101 */  OCAML_PUSHACC1,
  /* 102 */  OCAML_C_CALL1, 1,
  /* 104 */  OCAML_PUSHACC5,
  /* 105 */  OCAML_ADDINT,
  /* 106 */  OCAML_PUSHACC4,
  /* 107 */  OCAML_PUSHCONST0,
  /* 108 */  OCAML_PUSHACC, 8,
  /* 110 */  OCAML_C_CALL5, 2,
  /* 112 */  OCAML_ACC1,
  /* 113 */  OCAML_PUSHACC6,
  /* 114 */  OCAML_PUSHACC6,
  /* 115 */  OCAML_PUSHACC, 8,
  /* 117 */  OCAML_PUSHACC4,
  /* 118 */  OCAML_C_CALL1, 1,
  /* 120 */  OCAML_PUSHACC, 8,
  /* 122 */  OCAML_ADDINT,
  /* 123 */  OCAML_ADDINT,
  /* 124 */  OCAML_PUSHACC6,
  /* 125 */  OCAML_PUSHOFFSETCLOSURE0,
  /* 126 */  OCAML_APPTERM, 5, 12,
  /* 129 */  OCAML_ACC0,
  /* 130 */  OCAML_C_CALL1, 1,
  /* 132 */  OCAML_PUSHACC4,
  /* 133 */  OCAML_PUSHACC4,
  /* 134 */  OCAML_PUSHCONST0,
  /* 135 */  OCAML_PUSHACC4,
  /* 136 */  OCAML_C_CALL5, 2,
  /* 138 */  OCAML_ACC2,
  /* 139 */  OCAML_RETURN, 7,
  /* 141 */  OCAML_ACC0,
  /* 142 */  OCAML_RETURN, 5,
  /* 144 */  OCAML_RESTART,
  /* 145 */  OCAML_GRAB, 1,
  /* 147 */  OCAML_ACC1,
  /* 148 */  OCAML_BRANCHIFNOT_1B, 22,
  /* 150 */  OCAML_ACC0,
  /* 151 */  OCAML_C_CALL1, 1,
  /* 153 */  OCAML_PUSHACC2,
  /* 154 */  OCAML_PUSHACC1,
  /* 155 */  OCAML_PUSHACC3,
  /* 156 */  OCAML_PUSHCONST0,
  /* 157 */  OCAML_PUSHACC6,
  /* 158 */  OCAML_PUSHACC5,
  /* 159 */  OCAML_PUSHCONST0,
  /* 160 */  OCAML_PUSHGETFLASHGLOBAL_1B, 5,
  /* 162 */  OCAML_APPLY3,
  /* 163 */  OCAML_C_CALL1, 3,
  /* 165 */  OCAML_PUSHGETFLASHGLOBAL_1B, 6,
  /* 167 */  OCAML_APPTERM, 5, 8,
  /* 170 */  OCAML_GETFLASHGLOBAL_1B, 7,
  /* 172 */  OCAML_RETURN, 2,
  /* 174 */  OCAML_RESTART,
  /* 175 */  OCAML_GRAB, 1,
  /* 177 */  OCAML_ACC1,
  /* 178 */  OCAML_PUSHACC1,
  /* 179 */  OCAML_GEINT,
  /* 180 */  OCAML_BRANCHIFNOT_1B, 5,
  /* 182 */  OCAML_ACC0,
  /* 183 */  OCAML_RETURN, 2,
  /* 185 */  OCAML_GETFLASHGLOBAL_1B, 8,
  /* 187 */  OCAML_PUSHGETFLASHGLOBAL_1B, 3,
  /* 189 */  OCAML_APPTERM1, 3,
  /* 191 */  OCAML_RESTART,
  /* 192 */  OCAML_GRAB, 1,
  /* 194 */  OCAML_ACC0,
  /* 195 */  OCAML_C_CALL1, 3,
  /* 197 */  OCAML_PUSHCONST0,
  /* 198 */  OCAML_PUSHACC2,
  /* 199 */  OCAML_OFFSETINT_1B, (opcode_t) -1,
  /* 201 */  OCAML_PUSH,
  /* 202 */  OCAML_PUSHACC2,
  /* 203 */  OCAML_GTINT,
  /* 204 */  OCAML_BRANCHIF_1B, 19,
  /* 206 */  OCAML_CHECK_SIGNALS,
  /* 207 */  OCAML_ACC1,
  /* 208 */  OCAML_PUSHACC5,
  /* 209 */  OCAML_APPLY1,
  /* 210 */  OCAML_PUSHACC2,
  /* 211 */  OCAML_PUSHACC4,
  /* 212 */  OCAML_SETBYTESCHAR,
  /* 213 */  OCAML_ACC1,
  /* 214 */  OCAML_PUSH,
  /* 215 */  OCAML_OFFSETINT_1B, 1,
  /* 217 */  OCAML_ASSIGN, 2,
  /* 219 */  OCAML_ACC1,
  /* 220 */  OCAML_NEQ,
  /* 221 */  OCAML_BRANCHIF_1B, (opcode_t) -15,
  /* 223 */  OCAML_CONST0,
  /* 224 */  OCAML_POP, 2,
  /* 226 */  OCAML_ACC0,
  /* 227 */  OCAML_RETURN, 3,
  /* 229 */  OCAML_RESTART,
  /* 230 */  OCAML_GRAB, 1,
  /* 232 */  OCAML_ACC1,
  /* 233 */  OCAML_BRANCHIFNOT_1B, 10,
  /* 235 */  OCAML_ACC1,
  /* 236 */  OCAML_GETFIELD1,
  /* 237 */  OCAML_PUSHACC1,
  /* 238 */  OCAML_OFFSETINT_1B, 1,
  /* 240 */  OCAML_PUSHOFFSETCLOSURE0,
  /* 241 */  OCAML_APPTERM2, 4,
  /* 243 */  OCAML_ACC0,
  /* 244 */  OCAML_RETURN, 2,
  /* 246 */  OCAML_RESTART,
  /* 247 */  OCAML_GRAB, 1,
  /* 249 */  OCAML_ACC0,
  /* 250 */  OCAML_BRANCHIFNOT_1B, 12,
  /* 252 */  OCAML_ACC1,
  /* 253 */  OCAML_PUSHACC1,
  /* 254 */  OCAML_GETFIELD0,
  /* 255 */  OCAML_MAKEBLOCK2, 0,
  /* 257 */  OCAML_PUSHACC1,
  /* 258 */  OCAML_GETFIELD1,
  /* 259 */  OCAML_PUSHOFFSETCLOSURE0,
  /* 260 */  OCAML_APPTERM2, 4,
  /* 262 */  OCAML_ACC1,
  /* 263 */  OCAML_RETURN, 2,
  /* 265 */  OCAML_RESTART,
  /* 266 */  OCAML_GRAB, 1,
  /* 268 */  OCAML_ACC1,
  /* 269 */  OCAML_BRANCHIFNOT_1B, 14,
  /* 271 */  OCAML_ACC1,
  /* 272 */  OCAML_GETFIELD1,
  /* 273 */  OCAML_PUSHACC1,
  /* 274 */  OCAML_PUSHACC3,
  /* 275 */  OCAML_GETFIELD0,
  /* 276 */  OCAML_PUSHENVACC1,
  /* 277 */  OCAML_APPLY1,
  /* 278 */  OCAML_MAKEBLOCK2, 0,
  /* 280 */  OCAML_PUSHOFFSETCLOSURE0,
  /* 281 */  OCAML_APPTERM2, 4,
  /* 283 */  OCAML_ACC0,
  /* 284 */  OCAML_RETURN, 2,
  /* 286 */  OCAML_RESTART,
  /* 287 */  OCAML_GRAB, 1,
  /* 289 */  OCAML_ACC0,
  /* 290 */  OCAML_CLOSUREREC_1B, 1, 1, (opcode_t) -24,
  /* 294 */  OCAML_ACC2,
  /* 295 */  OCAML_PUSHCONST0,
  /* 296 */  OCAML_PUSHACC2,
  /* 297 */  OCAML_APPTERM2, 5,
  /* 299 */  OCAML_CONST0,
  /* 300 */  OCAML_PUSHACC1,
  /* 301 */  OCAML_PUSHGETFLASHGLOBAL_1B, 9,
  /* 303 */  OCAML_APPTERM2, 3,
  /* 305 */  OCAML_RESTART,
  /* 306 */  OCAML_GRAB, 1,
  /* 308 */  OCAML_ACC0,
  /* 309 */  OCAML_BRANCHIFNOT_1B, 17,
  /* 311 */  OCAML_ACC1,
  /* 312 */  OCAML_BRANCHIF_1B, 6,
  /* 314 */  OCAML_ACC0,
  /* 315 */  OCAML_GETFIELD0,
  /* 316 */  OCAML_RETURN, 2,
  /* 318 */  OCAML_ACC1,
  /* 319 */  OCAML_OFFSETINT_1B, (opcode_t) -1,
  /* 321 */  OCAML_PUSHACC1,
  /* 322 */  OCAML_GETFIELD1,
  /* 323 */  OCAML_PUSHOFFSETCLOSURE0,
  /* 324 */  OCAML_APPTERM2, 4,
  /* 326 */  OCAML_GETFLASHGLOBAL_1B, 10,
  /* 328 */  OCAML_PUSHGETFLASHGLOBAL_1B, 11,
  /* 330 */  OCAML_APPTERM1, 3,
  /* 332 */  OCAML_RESTART,
  /* 333 */  OCAML_GRAB, 1,
  /* 335 */  OCAML_ACC1,
  /* 336 */  OCAML_BLEINT_1B, 0, 9,
  /* 339 */  OCAML_GETFLASHGLOBAL_1B, 12,
  /* 341 */  OCAML_PUSHGETFLASHGLOBAL_1B, 3,
  /* 343 */  OCAML_APPTERM1, 3,
  /* 345 */  OCAML_CLOSUREREC_1B, 1, 0, (opcode_t) -39,
  /* 349 */  OCAML_ACC2,
  /* 350 */  OCAML_PUSHACC2,
  /* 351 */  OCAML_PUSHACC2,
  /* 352 */  OCAML_APPTERM2, 5,
  /* 354 */  OCAML_ACC0,
  /* 355 */  OCAML_PUSHCONST0,
  /* 356 */  OCAML_PUSHGETFLASHGLOBAL_1B, 13,
  /* 358 */  OCAML_APPTERM2, 3,
  /* 360 */  OCAML_ACC0,
  /* 361 */  OCAML_C_CALL1, 4,
  /* 363 */  OCAML_RETURN, 1,
  /* 365 */  OCAML_ACC0,
  /* 366 */  OCAML_C_CALL1, 5,
  /* 368 */  OCAML_RETURN, 1,
  /* 370 */  OCAML_RESTART,
  /* 371 */  OCAML_GRAB, 2,
  /* 373 */  OCAML_ACC0,
  /* 374 */  OCAML_PUSHCONST0,
  /* 375 */  OCAML_GTINT,
  /* 376 */  OCAML_BRANCHIF_1B, 17,
  /* 378 */  OCAML_ACC0,
  /* 379 */  OCAML_PUSHCONSTINT_1B, 4,
  /* 381 */  OCAML_LTINT,
  /* 382 */  OCAML_BRANCHIF_1B, 11,
  /* 384 */  OCAML_ACC1,
  /* 385 */  OCAML_PUSHCONST0,
  /* 386 */  OCAML_GTINT,
  /* 387 */  OCAML_BRANCHIF_1B, 6,
  /* 389 */  OCAML_ACC1,
  /* 390 */  OCAML_PUSHCONSTINT_1B, 4,
  /* 392 */  OCAML_LTINT,
  /* 393 */  OCAML_BRANCHIFNOT_1B, 7,
  /* 395 */  OCAML_GETFLASHGLOBAL_1B, 14,
  /* 397 */  OCAML_PUSHGETFLASHGLOBAL_1B, 3,
  /* 399 */  OCAML_APPLY1,
  /* 400 */  OCAML_ACC2,
  /* 401 */  OCAML_PUSHACC2,
  /* 402 */  OCAML_PUSHACC2,
  /* 403 */  OCAML_C_CALL3, 6,
  /* 405 */  OCAML_RETURN, 3,
  /* 407 */  OCAML_ACC0,
  /* 408 */  OCAML_PUSHENVACC1,
  /* 409 */  OCAML_PUSHGETFLASHGLOBAL_1B, 15,
  /* 411 */  OCAML_APPLY2,
  /* 412 */  OCAML_BRANCHIFNOT_1B, 9,
  /* 414 */  OCAML_CONSTINT_2B, 0, 255,
  /* 417 */  OCAML_PUSHGETFLASHGLOBAL_1B, 16,
  /* 419 */  OCAML_APPTERM1, 2,
  /* 421 */  OCAML_CONST0,
  /* 422 */  OCAML_PUSHGETFLASHGLOBAL_1B, 16,
  /* 424 */  OCAML_APPTERM1, 2,
  /* 426 */  OCAML_ACC0,
  /* 427 */  OCAML_PUSHGETFLASHGLOBAL_1B, 17,
  /* 429 */  OCAML_APPLY1,
  /* 430 */  OCAML_PUSHCONSTINT_1B, 5,
  /* 432 */  OCAML_NEQ,
  /* 433 */  OCAML_BRANCHIFNOT_1B, 7,
  /* 435 */  OCAML_GETFLASHGLOBAL_1B, 18,
  /* 437 */  OCAML_PUSHGETFLASHGLOBAL_1B, 3,
  /* 439 */  OCAML_APPLY1,
  /* 440 */  OCAML_ACC0,
  /* 441 */  OCAML_CLOSURE_1B, 1, (opcode_t) -34,
  /* 444 */  OCAML_PUSHCONSTINT_1B, 5,
  /* 446 */  OCAML_PUSHGETFLASHGLOBAL_1B, 19,
  /* 448 */  OCAML_APPTERM2, 3,
  /* 450 */  OCAML_ACC0,
  /* 451 */  OCAML_PUSHGETFLASHGLOBAL_1B, 17,
  /* 453 */  OCAML_APPLY1,
  /* 454 */  OCAML_PUSHCONSTINT_1B, 5,
  /* 456 */  OCAML_NEQ,
  /* 457 */  OCAML_BRANCHIFNOT_1B, 7,
  /* 459 */  OCAML_GETFLASHGLOBAL_1B, 20,
  /* 461 */  OCAML_PUSHGETFLASHGLOBAL_1B, 3,
  /* 463 */  OCAML_APPLY1,
  /* 464 */  OCAML_ACC0,
  /* 465 */  OCAML_PUSH,
  /* 466 */  OCAML_CLOSURE_1B, 0, (opcode_t) -40,
  /* 469 */  OCAML_PUSHGETFLASHGLOBAL_1B, 21,
  /* 471 */  OCAML_APPLY2,
  /* 472 */  OCAML_PUSHGETFLASHGLOBAL_1B, 22,
  /* 474 */  OCAML_APPLY1,
  /* 475 */  OCAML_PUSHCONST0,
  /* 476 */  OCAML_C_CALL1, 3,
  /* 478 */  OCAML_PUSHGETFLASHGLOBAL_1B, 23,
  /* 480 */  OCAML_APPLY2,
  /* 481 */  OCAML_PUSH,
  /* 482 */  OCAML_C_CALL1, 7,
  /* 484 */  OCAML_RETURN, 2,
  /* 486 */  OCAML_CONST0,
  /* 487 */  OCAML_RETURN, 1,
  /* 489 */  OCAML_ACC0,
  /* 490 */  OCAML_PUSHGETFLASHGLOBAL_1B, 24,
  /* 492 */  OCAML_APPLY1,
  /* 493 */  OCAML_C_CALL1, 4,
  /* 495 */  OCAML_RETURN, 1,
  /* 497 */  OCAML_CONST0,
  /* 498 */  OCAML_RETURN, 1,
  /* 500 */  OCAML_CONST1,
  /* 501 */  OCAML_C_CALL1, 8,
  /* 503 */  OCAML_RETURN, 1,
  /* 505 */  OCAML_CONST0,
  /* 506 */  OCAML_RETURN, 1,
  /* 508 */  OCAML_CONST0,
  /* 509 */  OCAML_C_CALL1, 8,
  /* 511 */  OCAML_RETURN, 1,
  /* 513 */  OCAML_CONST0,
  /* 514 */  OCAML_RETURN, 1,
  /* 516 */  OCAML_APPLY1,
  /* 517 */  OCAML_CONSTINT_1B, 42,
  /* 519 */  OCAML_PUSHGETFLASHGLOBAL_1B, 25,
  /* 521 */  OCAML_GETFIELD1,
  /* 522 */  OCAML_APPLY1,
  /* 523 */  OCAML_GETFLASHGLOBAL_1B, 26,
  /* 525 */  OCAML_PUSHGETFLASHGLOBAL_1B, 25,
  /* 527 */  OCAML_GETFIELD, 4,
  /* 529 */  OCAML_APPLY1,
  /* 530 */  OCAML_BRANCH_1B, 93,
  /* 532 */  OCAML_CHECK_SIGNALS,
  /* 533 */  OCAML_CONST0,
  /* 534 */  OCAML_PUSHGETFLASHGLOBAL_1B, 27,
  /* 536 */  OCAML_GETFIELD1,
  /* 537 */  OCAML_APPLY1,
  /* 538 */  OCAML_BRANCHIFNOT_1B, 21,
  /* 540 */  OCAML_CONST1,
  /* 541 */  OCAML_PUSHCONST3,
  /* 542 */  OCAML_PUSHCONST0,
  /* 543 */  OCAML_PUSHGETFLASHGLOBAL_1B, 25,
  /* 545 */  OCAML_GETFIELD, 6,
  /* 547 */  OCAML_APPLY3,
  /* 548 */  OCAML_CONST0,
  /* 549 */  OCAML_PUSHCONSTINT_1B, 4,
  /* 551 */  OCAML_PUSHCONST0,
  /* 552 */  OCAML_PUSHGETFLASHGLOBAL_1B, 25,
  /* 554 */  OCAML_GETFIELD, 6,
  /* 556 */  OCAML_APPLY3,
  /* 557 */  OCAML_BRANCH_1B, 19,
  /* 559 */  OCAML_CONST0,
  /* 560 */  OCAML_PUSHCONST3,
  /* 561 */  OCAML_PUSHCONST0,
  /* 562 */  OCAML_PUSHGETFLASHGLOBAL_1B, 25,
  /* 564 */  OCAML_GETFIELD, 6,
  /* 566 */  OCAML_APPLY3,
  /* 567 */  OCAML_CONST1,
  /* 568 */  OCAML_PUSHCONSTINT_1B, 4,
  /* 570 */  OCAML_PUSHCONST0,
  /* 571 */  OCAML_PUSHGETFLASHGLOBAL_1B, 25,
  /* 573 */  OCAML_GETFIELD, 6,
  /* 575 */  OCAML_APPLY3,
  /* 576 */  OCAML_CONST0,
  /* 577 */  OCAML_PUSHGETFLASHGLOBAL_1B, 28,
  /* 579 */  OCAML_GETFIELD1,
  /* 580 */  OCAML_APPLY1,
  /* 581 */  OCAML_BRANCHIFNOT_1B, 23,
  /* 583 */  OCAML_CONST1,
  /* 584 */  OCAML_PUSHCONST3,
  /* 585 */  OCAML_PUSHCONSTINT_1B, 4,
  /* 587 */  OCAML_PUSHGETFLASHGLOBAL_1B, 25,
  /* 589 */  OCAML_GETFIELD, 6,
  /* 591 */  OCAML_APPLY3,
  /* 592 */  OCAML_CONST0,
  /* 593 */  OCAML_PUSHCONSTINT_1B, 4,
  /* 595 */  OCAML_PUSHCONSTINT_1B, 4,
  /* 597 */  OCAML_PUSHGETFLASHGLOBAL_1B, 25,
  /* 599 */  OCAML_GETFIELD, 6,
  /* 601 */  OCAML_APPLY3,
  /* 602 */  OCAML_BRANCH_1B, 21,
  /* 604 */  OCAML_CONST0,
  /* 605 */  OCAML_PUSHCONST3,
  /* 606 */  OCAML_PUSHCONSTINT_1B, 4,
  /* 608 */  OCAML_PUSHGETFLASHGLOBAL_1B, 25,
  /* 610 */  OCAML_GETFIELD, 6,
  /* 612 */  OCAML_APPLY3,
  /* 613 */  OCAML_CONST1,
  /* 614 */  OCAML_PUSHCONSTINT_1B, 4,
  /* 616 */  OCAML_PUSHCONSTINT_1B, 4,
  /* 618 */  OCAML_PUSHGETFLASHGLOBAL_1B, 25,
  /* 620 */  OCAML_GETFIELD, 6,
  /* 622 */  OCAML_APPLY3,
  /* 623 */  OCAML_CONST1,
  /* 624 */  OCAML_BRANCHIF_1B, (opcode_t) -92,
  /* 626 */  OCAML_STOP
};

#include </Users/ruiwenwang/Desktop/OMicroB/src/byterun/vm/runtime.c>

PROGMEM void * const ocaml_primitives[OCAML_PRIMITIVE_NUMBER] = {
  /*  0 */  (void *) &caml_string_of_int,
  /*  1 */  (void *) &caml_ml_bytes_length,
  /*  2 */  (void *) &caml_blit_bytes,
  /*  3 */  (void *) &caml_create_bytes,
  /*  4 */  (void *) &caml_microbit_print_string,
  /*  5 */  (void *) &caml_microbit_clear_screen,
  /*  6 */  (void *) &caml_microbit_write_pixel,
  /*  7 */  (void *) &caml_microbit_print_image,
  /*  8 */  (void *) &caml_microbit_button_is_pressed,
};
